

services:

  python:
    container_name: python
    build: python/build/.
    volumes:
      - ./python:/python
      - ./data:/data
    environment:
      - JIRA_TOKEN
      - JIRA_EMAIL
      - JIRA_PROJECT
      - JIRA_STATUSES
      - JIRA_FIELDS
      - MAX_RESULTS=10000
    command: python3 main.py
